services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "hypercorn webhook_bot:flask_app --bind 0.0.0.0:5000 --workers 1 --worker-class asyncio"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
